system:
  num_client: 100
  num_local_class: 2
  dataset: "MNIST"
  model: "LeNet"
  i_seed: 235235
  num_round: 100
  res_root: "results"

client:
  fed_algo: "FedNova"
  lr: 0.01
  batch_size: 128
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2