#system:
#  num_client: 100
#  num_local_class: 2
#  dataset: "MNIST"
#  model: "LeNet"
#  i_seed: 235235
#  num_round: 100
#  res_root: "results"
#
#client:
#  fed_algo: "SCAFFOLD"
#  lr: 0.01
#  batch_size: 128
#  num_local_epoch: 3
#  momentum: 0.9
#  num_worker: 2

# Cifar10
system:
  num_client: 20
  num_local_class: 4
  dataset: "CIFAR10"
  model: "AlexCifarNet"
  i_seed: 10002
  num_round: 100
  res_root: "results/1220"

client:
  fed_algo: "SCAFFOLD"
  lr: 0.005
  batch_size: 128
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2